package myChessGame2016;

import data.Player;

/*
	CHESSGAME2016 - MY ATTEMPT AT THE CLASSIC GAME OF CHESS!
	THE GAME MAY BE PLAYED BY TWO PLAYERS, WHO WILL BE ASSIGNED
	A SIDE (PLAYER1 - WHITE, PLAYER 2 - BLACK). AS OF NOW, A 
	PLAYER CAN MAKE A MOVE. THE LOGIC IS YET TO BE IMPLEMENTED.
	
	POINTS TO NOTE - THE GAMEMANAGER CLASS WILL THE BE SINGLE POINT
	THAT BEGINS THE GAME, AND THEN DELEGATE THE RESPONSIBILITIES TO 
	OTHER COMPONENTS. 
	
	QUICK LOGIC - BOARD(BOARD.JAVA) CONTAINS 64 SQUARES (BOARDSQUARE.JAVA)
	AND WE MAY HAVE UP TO 32 PIECES ON THE BOARD (CHESSPIECE) WITH VARIOUS
	VALUES (PIECESANDVALUES.JAVA). THE PLAYER(PLAYER.JAVA) WILL THEN BE ABLE TO INTERACT
	WITH THE BOARD AND THE PIECES THROUGH THE 'MOVE' ACTION.
 */
public class ChessGame2016 {
	
	public static void main(String[] args) {
		// SET THE TWO PLAYERS, AND BEGIN THE GAME. REST OF THE GAME IS
		// HANDLED BY THE GAMEMANAGER CLASS
		Player p1 = new Player(1);
		Player p2 = new Player(2);

		GameManager chessManager = new GameManager();
		chessManager.beginGame();
	}

	
}